on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    uses: anhhao1996/playwright-test/.github/workflows/run-tests.yml@master
    with:
      browser: chrome        # hardcoded value
    secrets: inherit